import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import parse from "node-html-parser";
import styles from "../styles/Home.module.css";
import React from "react";
import dynamic from "next/dynamic";

const HeatMapView = dynamic(() => import("components/HeatMapView"), {
  ssr: false,
});

const Home: NextPage = ({ out }: any) => {
  const totalSellAmount = React.useMemo(() => {
    return out.reduce((acc: number, cur: any) => {
      return acc + cur.totSellamnt;
    }, 0);
  }, [out]);

  const total = React.useMemo(() => {
    return out.reduce(
      (acc: any, cur: any) => {
        acc.sellAmount = acc.sellAmount + cur.totSellamnt;
        acc.winnerCount = acc.winnerCount + cur.firstPrzwnerCo;
        acc.firstWinAmount = acc.firstWinAmount + cur.firstWinamnt;
        return acc;
      },
      {
        sellAmount: 0,
        winnerCount: 0,
        firstWinAmount: 0,
      }
    );
  }, [out]);

  const top10 = React.useMemo(() => {
    return out.reverse().slice(0, 10);
  }, [out]);

  const numberAcc = React.useMemo(() => {
    return out.reduce((acc, cur) => {
      const numbers = [
        cur.drwtNo1,
        cur.drwtNo2,
        cur.drwtNo3,
        cur.drwtNo4,
        cur.drwtNo5,
        cur.drwtNo6,
      ];
      numbers.forEach((number) => {
        if (!acc[number]) {
          acc[number] = 0;
        }
        acc[number] = acc[number] + 1;
      });
      return acc;
    });
  }, [out]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Total sell amout: {total.sellAmount}</h1>
      <h1>Total winnerCount: {total.winnerCount}</h1>

      <h1>Total firstWinAmount: {total.firstWinAmount}</h1>
      <h2>{JSON.stringify(numberAcc)}</h2>
      {/* <LottoAccMapView /> */}
      <HeatMapView item={out} />

      <pre>{JSON.stringify(top10, undefined, "\t")}</pre>
    </div>
  );
};

export const getStaticProps = async () => {
  const res = await fetch("https://kyun.github.io/lotto_analysis/merge");
  const html = await res.text();
  const root = parse(html);
  const text = root.querySelector("pre")?.text;
  return {
    props: {
      // props for your component
      out: JSON.parse(text ?? "{}"),
    },
  };
};

export default Home;
